"""Updated table name

Revision ID: 602363ac70af
Revises: 85a452161b9b
Create Date: 2026-07-13 23:58:42.289416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602363ac70af'
down_revision = '85a452161b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('associated_documents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associated_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('documents')
    # ### end Alembic commands ###
